"""add brand subtitles

Revision ID: 2c8a2e39a155
Revises: 
Create Date: 2025-09-15 21:21:58.812920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c8a2e39a155'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle_en', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('subtitle_ru', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('subtitle_tk', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.drop_column('subtitle_tk')
        batch_op.drop_column('subtitle_ru')
        batch_op.drop_column('subtitle_en')

    # ### end Alembic commands ###
